### PR TITLE
DON'T MERGE #510 Setting up MapStruct and Lombok within one compilation unit

### PR DESCRIPTION
**Pull request by gunnarmorling**
Playground for SPI geared towards Lombok

### CODE REVIEW

**Comment by agudian** [comment]
We can update this PR as well, with the released versions of Lombok and MapStruct... :) Well, and the updated license headers... 😁

**Comment by gunnarmorling** [comment]
Yepp, next thing I'll do :)

**Comment by gunnarmorling** [comment]
Rebased and applied :)

**Comment by agudian** [comment]
> Rebased and applied :)

Looks good! 👍

**Pull request closed without merging**
