### PR TITLE
ignore all but name based

### PR DESCRIPTION
**Pull request by sjaakd**
Shows how a methods can be organised into 2 mappers to avoid  ignoring numerous target properties (there's only one here). 

The example has a drawback (that is shown as well). Name-based-automatic mapping still occurs.

### CODE REVIEW

**Comment by sjaakd** [comment]
can be closed if ignoreAll is implemented.

**Comment by filiphr** [comment]
We can adapt this to work with that ;)

**Comment by sjaakd** [comment]
> We can adapt this to work with that ;)

That's true.. I'll update it when we're done with the issue and add something meaningful

**Comment by sjaakd** [comment]
@filiphr .. think we can  still use this example (as is).

**Comment by filiphr** [comment]
If you think that we should not display the new functionality from 1.3.0.Beta1 then go for it and merge it. 

Maybe only update the mapstruct version to 1.3.0.Beta1 before merging

**Comment by sjaakd** [comment]
> If you think that we should not display the new functionality from 1.3.0.Beta1 then go for it and merge it.

It more that this covers a case were you have lots of name based mappings which you don't want to repeat.. I just replied to an [issue](https://github.com/mapstruct/mapstruct/issues/1488) regarding this.

**Pull request merged**
