### PR TITLE
Add mappers to the test sources

### LINKED ISSUE #21: Provide example for using MapStruct on Maven test sources
It seems not to work out of the box: http://stackoverflow.com/questions/42713870/mapstruct-mapper-in-src-test-java-not-generated-by-maven-build

### PR DESCRIPTION
**Pull request by filiphr**
Fixes #21.

This PR adds some mappers to the test sources (`src/test/java`) in some of the modules

### CODE REVIEW

**Comment by filiphr** [comment]
I have updated some of the dependencies to 1.2.0-SNAPSHOT because of the fix for https://github.com/mapstruct/mapstruct/issues/1121. 

With the maven compiler it works out of the box.

With: 

```
<groupId>org.bsc.maven</groupId>
<artifactId>maven-processor-plugin</artifactId>
```

one should explicitly invoke the `process-test` goal.

**Comment by agudian** [comment]
How about adding a test mapper only to one project that uses the processor-plugin, as it's working out of the box for the compiler-plugin already?
Otherwise we just have some additional classes lying around in the different projects, although they don't add any value to the specific example (e.g. the lombok, fieldaccess or cycle examples all stand very well on their own).
For the processor plugin example, you could also add a small comment explaining that the additional execution in phase process-test-resources is only required if you want to generate mappers from `src/test/java`.

**Comment by filiphr** [comment]
@agudian I agree with you. I will keep the `mapstruct-update-methods-1` as an example for the processor plugin. I added more only because in the SO question the OP was using the maven compiler. However, thinking more about it, maybe the compiler was not invoked correctly.

**Comment by agudian** [comment]
> However, thinking more about it, maybe the compiler was not invoked correctly.

Yes, something else might have been fishy there... The compiler plugin hands over the processor path to the javac compiler in the same way for both the `compile` and `testCompile` goal... Perhaps the user can provide a complete example where it's not working for him, then we could check in more detail what's wrong there...

**Pull request merged**
