### PR TITLE
Aggregator, version updates and Gradled Lombok

### PR DESCRIPTION
**Pull request by agudian**
#18 and #19 in one PR... :)

### CODE REVIEW

**Comment by agudian** [comment]
That still works, Filip 🙂. I used this to update all the versions in one go:
http://www.mojohaus.org/versions-maven-plugin/use-latest-versions-mojo.html

Still the examples are fully self-contained and don't need a common parent or bom-pom.

**Comment by filiphr** [comment]
@agudian I didn't know about this goal of the versions plugin :). 

You can merge when you want :)

**Comment by agudian** [comment]
Great, thanks for reviewing! :)

**Comment by gunnarmorling** [comment]
Nice one, thanks!

**Pull request merged**
