### PR TITLE
Adding examples for using MapStruct with complex nested bean mappings

### PR DESCRIPTION
**Pull request by filiphr**

### CODE REVIEW

**Comment by agudian** [comment]
Are the additional files in `mapstruct-updatemethods-1` added on purpose?

**Comment by filiphr** [comment]
No they are not. They are a mistake. I will modify the PR, sorry

**Comment by agudian** [comment]
You can also directly add 1.2.0.Beta1 in the pom then... :)

**Comment by filiphr** [comment]
Done 😄

**Comment by gunnarmorling** [comment]
Merged; thanks!

**Pull request merged**
